from pathlib import Path

class InterfaceResources:

    generated_keyword = "This file is generated by a tool. Do not edit directly."


class AdapiResources(InterfaceResources):

    def __init__(self, path: str):
        self.base_path = Path(path)
        self.list_path = self.base_path / "list"
        self.type_path = self.base_path / "types"

    def clean(self):
        for path in self.base_path.glob("**/*.md"):
            if path.is_file():
                with path.open() as fp:
                    line = fp.readline()
                if self.generated_keyword in line:
                    print(path)
                    path.unlink()
